name: Fetch JBZD Memes

on:
  workflow_dispatch: # pozwala uruchomić ręcznie w GitHub

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run fetch script
        run: python jbzd-memes-data-1.py # zmień w repo2 i repo3 odpowiednio

      - name: Commit CSV
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add *.csv
          git commit -m "Add latest memes CSV" || echo "No changes to commit"
          git push
